### ISSUE TITLE
Preferences & Element Studio Option disappeared.

### ISSUE THREAD

**Issue by ahsanbod** [breakdance/breakdance#28]
Under builder settings there used to be two more options that disappeared for all my sites. 

Preferences & Element Studio

I need to upload custom font that used to be under preferences. Is there any other way to upload custom font?

![image (9)](https://github.com/breakdance/breakdance/assets/80476770/495322ed-2c09-4358-b702-a8f59028316f)

**Comment by jonschlinkert** [comment]
hi @ahsanbod I think you created an issue on the wrong library.
