### ISSUE TITLE
Breakdance in browser

### ISSUE THREAD

**Issue by stevebeisner** [breakdance/breakdance#5]
I was looking to improve my HTML to Markdown conversion for a web 
application I have, but it appears that after an npm install of breakdance
that importing the module causes a "TypeError: fs.readdirSync is not a function".

My suspicion is that it's because the breakdance CLI is part of the
module, even though it's not required if one is calling the 
breakdance( html_text) function in a browser context.

**Comment by jonschlinkert** [comment]
done, I've externalized the CLI code to [breakdance-cli](https://github.com/breakdance/breakdance-cli). Thanks for the issue and for using breakdance!

**Comment by hibig** [comment]
> done, I've externalized the CLI code to [breakdance-cli](https://github.com/breakdance/breakdance-cli). Thanks for the issue and for using breakdance!

I install the cli -S but the problem is appears
